### ISSUE TITLE
Pot size misscalculate when Re-raise

### ISSUE THREAD

**Issue by sevendeuceoffsuit** [b-inary/wasm-postflop#3]
When re-raise 120 on pot 280, shows pot 360 instead of 400.
other re-raise situation is same.
![無題](https://user-images.githubusercontent.com/116118887/196544218-648e8478-9bad-42aa-b71e-05a2349aadda.png)

**Comment by b-inary** [comment]
Sorry for the late response.

This seems correct to me:
- Initial state (1st figure): (OOP stack = 1000) / IP stack = 1000 / Pot = 80
- IP bets 40 (2nd figure): OOP stack = 1000 / (IP stack = 960) / Pot = 120 (= 80 + 0 + 40)
- OOP raises 80 (3rd figure): (OOP stack = 920) / IP stack = 960 / Pot = 200 (= 80 + 80 + 40)
- IP raises 120 (4th figure): OOP stack = 920 / (IP stack = 880) / Pot = 280 (= 80 + 80 + 120)
- OOP raises 160 (5th figure): (OOP stack = 840) / IP stack = 880 / Pot = 360 (= 80 + 160 + 120)

Note that "IP raises 120" does not increase the pot by 120 because IP has already put 40 into the pot. The same goes for "OOP raises 160".

**Comment by sevendeuceoffsuit** [comment]
b-inary,
Thank you and sorry for my misunderstanding. educational situation for me!
